version: '3.8'

services:
  backend-api:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-pi:5432/codigo_pi_db
      - SPRING_DATASOURCE_USERNAME=user_pi
      - SPRING_DATASOURCE_PASSWORD=pass_pi
    depends_on:
      - db-pi

  db-pi:
    build: ./backend/db
    environment:
      POSTGRES_DB: codigo_pi_db
      POSTGRES_USER: user_pi
      POSTGRES_PASSWORD: pass_pi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
