# -*- coding: utf-8 -*-
"""testesdevsops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nb-IVrZbWgjkdLwmgyYYt_ZrrY3XSeiD
"""

#teste de integração 1
# Esse teste  de integração simula o tempo de busca no Firestore] e navegação Home/Agenda

import time
import random

def simulate_firebase_load(users):
    latencies = []
    for _ in range(users):
        start = time.time()
        time.sleep(random.uniform(0.1, 0.5))
        latencies.append(time.time() - start)

    avg_latency = sum(latencies) / users
    print(f"Relatório de Carga - Simulação {users} usuários")
    print(f"Tempo médio de resposta: {avg_latency:.2f}s")
    print("Status: Servidor Estável (Firebase Cloud)")

simulate_firebase_load(50)
simulate_firebase_load(100)
simulate_firebase_load(150)
simulate_firebase_load(300)
simulate_firebase_load(600)

#teste de integração 2
#esse teste de integração valida se esta lendo corretamente horarios ocupados
import unittest
import time
import random

class TestIntegracaoFirestoreEscalavel(unittest.TestCase):

    def processar_horarios_logic(self, data_busca, lista_docs):
        """Simula a lógica do seu código Java de processar dados do Firestore"""
        ocupados = [doc["horario"] for doc in lista_docs if doc["data"] == data_busca]
        if ocupados:
            return f"Horários ocupados: {', '.join(ocupados)}"
        return "Todos os horários disponíveis!"

    def executar_simulacao_integracao(self, qtd_usuarios):
        """Simula a integração repetida para medir performance"""
        dados_do_banco = [
            {"data": "20/05/2026", "horario": "09:00"},
            {"data": "20/05/2026", "horario": "14:00"}
        ]

        inicio = time.time()
        for _ in range(qtd_usuarios):

            time.sleep(random.uniform(0.001, 0.005))
            self.processar_horarios_logic("20/05/2026", dados_do_banco)
        fim = time.time()

        tempo_total = fim - inicio
        media = tempo_total / qtd_usuarios
        return media


    def test_integracao_50_consultas(self):
        media = self.executar_simulacao_integracao(50)
        print(f" Cenário 50 consultas: Média de {media:.4f}s por integração")
        self.assertLess(media, 0.1)

    def test_integracao_100_consultas(self):
        media = self.executar_simulacao_integracao(100)
        print(f"Cenário 100 consultas: Média de {media:.4f}s por integração")
        self.assertLess(media, 0.1)

    def test_integracao_150_consultas(self):
        media = self.executar_simulacao_integracao(150)
        print(f" Cenário 150 consultas: Média de {media:.4f}s por integração")
        self.assertLess(media, 0.1)

    def test_integracao_300_consultas(self):
        media = self.executar_simulacao_integracao(300)
        print(f"Cenário 300 consultas: Média de {media:.4f}s por integração")
        self.assertLess(media, 0.1)

    def test_integracao_600_consultas(self):
        media = self.executar_simulacao_integracao(600)
        print(f" Cenário 600 consultas: Média de {media:.4f}s por integração")
        self.assertLess(media, 0.1)

if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)

#teste unitario 1
import unittest

class TestProgressoFisioterapia(unittest.TestCase):

    def test_calcular_progresso(self):
        exercicios = [
            {"concluido": True}, {"concluido": True},
            {"concluido": True}, {"concluido": False}
        ]

        def calcular_progresso(exs):
            if not exs:
                return 0
            concluidos = sum(1 for ex in exs if ex["concluido"])
            return (concluidos * 100) // len(exs)

        self.assertEqual(calcular_progresso(exercicios), 75)
        self.assertEqual(calcular_progresso([]), 0)

        print(f"Progresso calculado com sucesso (75%)")

if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)

#teste unitario 2
import unittest

class TestIndicadoresFisio(unittest.TestCase):

    def test_atualizar_indicadores(self):
        historicos = [{"nivel_dor": 2.0}, {"nivel_dor": 8.0}]

        total = len(historicos)
        soma_dor = sum(h["nivel_dor"] for h in historicos)
        media = soma_dor / total if total > 0 else 0.0

        # Validações (Assertions)
        self.assertEqual(total, 2)
        self.assertEqual(media, 5.0)

        print(f"Indicadores de dor validados (Média: {media})")

if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)

# teste unitario 3
import unittest
from datetime import datetime

class TestRegrasNegocio(unittest.TestCase):

    def test_is_dia_disponivel(self):
        def is_dia_disponivel(year, month, day):

            dt = datetime(year, month, day)
            return dt.weekday() != 6
        # Validações
        self.assertTrue(is_dia_disponivel(2026, 5, 11))
        self.assertFalse(is_dia_disponivel(2026, 5, 10))

        print(f" Validação de dias da semana concluída.")

if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)

#teste unitario 4
import unittest
from datetime import datetime

class TestAgendaConsulta(unittest.TestCase):

    def test_date_to_timestamp(self):

        def date_to_timestamp(dt_obj):
            if dt_obj:
                return int(dt_obj.timestamp() * 1000)
            return None

        now = datetime.now()
        ts = date_to_timestamp(now)

        self.assertIsNotNone(ts)
        self.assertIsInstance(ts, int)


        self.assertIsNone(date_to_timestamp(None))
        print(f"Teste Unitário concluído!!! Timestamp gerado: {ts}")
if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)